Order system
contekv/portfolio pull request #10
Opened 2020-09-13 11:52 UTC by contekv

コードレビューよろしくお願いします。

2020-09-13 12:00 UTC, contekv commented on app/controllers/orders_controller.rb
> +
単一のviewでpaginateを複数使うためallメソッドを使用していません。
viewにallメソッドでデータを引き渡してからpaginateもenum毎に分けることは出来ないと思っています...

2020-09-13 12:06 UTC, contekv commented on app/views/orders/index.html.erb
> +<%= paginate @orders3, param_name: "completed_page" %><hr>
やはりリファクタリング余地は多いでしょうか💦

2020-09-16 09:48 UTC, reiforu requested changes
遅れてしまいすいません！

結構実装できるようになってきましたね！
DRYの部分意識できるとなおよいです👍

2020-09-16 09:48 UTC, reiforu commented on app/controllers/orders_controller.rb
> +
12行目
10というマジックナンバーを使っていますね。修正しましょう👍

2020-09-16 09:48 UTC, reiforu commented on app/controllers/orders_controller.rb
> +end
28行目
これ失敗したらどうなるんでしょう？🤔

2020-09-16 09:48 UTC, reiforu commented on app/views/homes/show.html.erb
>  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
order_pathに@userが入っているようですけど、ここってOrderオブジェクトが入るのではないでしょうか？🤔

2020-09-16 09:48 UTC, reiforu commented on app/views/orders/index.html.erb
> +<%= paginate @completed_orders, param_name: "completed_page" %><hr>
ここですが、DRYにしたいですね。
パーシャルを1つ作って、そこにwaiting, running, arrival, completeのordersを渡せませんか？

2020-09-16 10:01 UTC, contekv commented on app/controllers/orders_controller.rb
> +
忘れていました💦
修正しておきます！

2020-09-16 10:05 UTC, contekv commented on app/controllers/orders_controller.rb
> +end
分岐処理で書いておきます💦

2020-09-16 10:53 UTC, contekv commented on app/views/homes/show.html.erb
>  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
Orderオブジェクトを渡すように変更しておきます！

2020-09-16 12:02 UTC, contekv commented on app/views/orders/index.html.erb
> +<%= paginate @completed_orders, param_name: "completed_page" %><hr>
確かに出来そうです！
DRYしてみます。

2020-09-17 02:35 UTC, reiforu requested changes
レビューしました！

2020-09-17 02:35 UTC, reiforu commented on app/views/homes/show.html.erb
>  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
あれ、すいません。order_pathのroute見せていただけますか？
userのidを参照するのであれば@userでかまいません。

ただorder_pathってorder#showに行くのかなと予想していて、
その場合渡したいidってOrderオブジェクトのidではないかなと。

2020-09-17 05:04 UTC, contekv commented on app/views/orders/index.html.erb
> +<%= paginate @completed_orders, param_name: "completed_page" %><hr>
falseで<h1>現在、受取済の商品はありません</h1>出力予定なので大丈夫です！
注文システムのみCSSまだなので仮決定状態ですけど💦

2020-09-17 14:25 UTC, reiforu approved these changes
LGTM

2020-09-17 14:25 UTC, reiforu commented on app/views/users/orders/index.html.erb
> +<%= link_to "注文　新規", new_order_path unless current_user.admin? %>
👍

2020-09-17 14:25 UTC, reiforu commented on app/views/homes/show.html.erb
>  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
namespaceの実装いいですね！
`users_user_orders_path(@user)`にuserが2回も出てきてちょっと気になりましたが、とりあえずはOKとします！
普通は`user_orders_path(@user)`になりそうな気もしますがまあOKです！

2020-09-17 15:08 UTC, merged