Revision
contekv/portfolio pull request #13
Opened 2020-09-22 07:25 UTC by contekv

2020-09-22 07:48 UTC, contekv commented on Gemfile
> +#gem "devise-i18n-views"
"devise-i18n-views"は"devise-i18n"にmergeされたみたいなので削除しました。

2020-09-22 07:51 UTC, contekv commented on app/controllers/users/registrations_controller.rb
> +    end
ゲストユーザーはプロフィール編集出来ないように追記しました。

2020-09-22 08:05 UTC, reiforu requested changes

2020-09-22 08:05 UTC, reiforu commented on app/models/user.rb
> +  end
13行目
guestという命名が微妙かなと思いました👀
何をしたいのかわかるような命名にしたいです！
あと、
```
  def self.guest(email)
    find_or_create_by!(email: email) do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
```
のほうが使い回せるのでいいですね👍

2020-09-22 08:05 UTC, reiforu commented on app/views/homes/show.html.erb
> +<%= button_to "プロフィール", user_path(@user), method: :get%>
基本的にmethod: :getなのでつける必要ないかなと思いましたが、つけないと動きませんか？🤔
get以外の場合は付ける必要がありますが。

2020-09-22 08:05 UTC, reiforu commented on app/views/medicines/_medicine.html.erb
>  <% end %><hr>
ここもですね。method: :get

2020-09-22 08:05 UTC, reiforu commented on config/routes.rb
> +  resources :orders, except: [:edit]
👍

2020-09-22 08:27 UTC, contekv commented on app/controllers/users/passwords_controller.rb
> +end
すみません、乱雑でしたね💦

2020-09-22 08:28 UTC, contekv commented on app/controllers/users/registrations_controller.rb
> +    end
ありがとうございます。
returnの挙動、分かっていないのでまた学習しておきます！

2020-09-22 08:29 UTC, contekv commented on app/models/user.rb
> +  end
勉強になります。
変更しておきますね！

2020-09-22 08:35 UTC, contekv commented on app/views/homes/show.html.erb
> +<%= button_to "プロフィール", user_path(@user), method: :get%>
button_toのみ変更した際、post扱いされてしまい動かなかったですね💦
rails6で変わったのですかね...

2020-09-22 08:50 UTC, contekv commented on app/views/medicines/_medicine.html.erb
>  <% end %><hr>
PR前の動作確認時、get指定しなければ何故かpost扱いされてしまったので指定していましたが改めて動作確認すると直っていました💦
外しておきます！

2020-09-28 02:17 UTC, reiforu requested changes

2020-09-28 02:17 UTC, reiforu commented on app/controllers/users/passwords_controller.rb
> +end
こちら、必要な部分だけ残そうとするとエラーが発生するのでしょうか？🤔

2020-09-28 02:17 UTC, reiforu commented on app/views/homes/show.html.erb
> +<%= button_to "プロフィール", user_path(@user), method: :get%>
それはbutton_toがデフォルトでpostの動作をするからです。
getの場合は基本的にlink_toを使って、それにボタンらしくみえるcssを適用するかなと👍

2020-09-28 03:53 UTC, contekv commented on app/controllers/users/passwords_controller.rb
> +end
今回update使って無いですね💦
削除しておきます。

2020-09-28 04:02 UTC, contekv commented on app/controllers/users/passwords_controller.rb
>        end
A or B 　←　AかBどちらか一方でも真であればredirectされると思って実装していましたが、それ以外のメールアドレスでも何故かredirectされるので、in?メソッド使用し解決させました。

2020-09-28 04:10 UTC, contekv commented on app/views/homes/show.html.erb
> +<%= button_to "プロフィール", user_path(@user), method: :get%>
デフォルトがpostなのですね
最初、CSSとの結合で苦戦した理由が理解できました！

2020-09-28 06:14 UTC, reiforu requested changes

2020-09-28 06:14 UTC, reiforu commented on app/controllers/users/passwords_controller.rb
> +end
あ、そうではなくて、new, create, editって何かご自身で手を加えたのでしょうか？
加えてないなら削除しましょう、ということです。devise側のnew, create, editを呼び出すので。

2020-09-28 11:08 UTC, contekv commented on app/controllers/users/passwords_controller.rb
> +end
すみません、devise知識不足でした。
確認しておきます。

2020-09-29 03:34 UTC, reiforu approved these changes
LGTMですがコンフリクト修正されていないので、その際に修正ミスるとエラー発生する可能性があります。
すいませんがそこは対応お願いします。

2020-09-30 02:12 UTC, closed without merging