Active storage
contekv/portfolio pull request #7
Opened 2020-08-25 07:54 UTC by contekv

コードレビューよろしくお願いします。

2020-08-25 08:00 UTC, contekv commented on app/controllers/users_controller.rb
>  end
DB処理が必要ないのでgetメソッドでcontrollerからpurgeメソッドで画像をdeleteしています。
これは良くない実装になっているかなと💦

2020-08-25 08:18 UTC, contekv commented on app/views/conversations/_messages.html.erb
>  <% end %>
ユーザー画像（conversation.user.avatar）が管理者の投稿メッセージにも表示されてしまっており、ユーザーと管理者のメッセージ別に画像を表示する方法が分からないです。
新たにconversatino.controllerでインスタンス定義しなくとも、@conversation(find(params[:id]))でuser取得出来ているので、@conversation.userで使い回し出来ると考えてはおりますが、解決策が見出せずにいます💦
<img width="408" alt="スクリーンショット 2020-08-25 17 12 25" src="https://user-images.githubusercontent.com/62380843/91149621-414b0400-e6f6-11ea-93dc-124797e2c704.png">

2020-08-25 10:55 UTC, reiforu requested changes

2020-08-25 10:55 UTC, reiforu commented on app/controllers/conversations_controller.rb
>      if @conversation.present?
15行目
変な空白はいってますね

2020-08-25 10:55 UTC, reiforu commented on app/controllers/users/registrations_controller.rb
>  end
9行目
updateならpurgeしてからattachしないといけないのかなと思ったんですけど、
attachだけでpurgeまで含めて行ってくれるのでしょうか？🤔

2020-08-25 10:55 UTC, reiforu commented on app/controllers/users_controller.rb
>  end
極力REST以外あまり実装したくはないですね。
purgeはgetでアクセスすると思うんですけど、画像削除専用ページがほしいならこれでいいですが、
例えばプロフィール更新ページなどで画像削除したい、というのであれば
def purgeを作るのではなく、def update内でpurgeするほうがいいですね。

purge自体、DB内の画像を削除するというDB処理をしているので、destroyとかupdateで行うほうがいいですね
ただここはusers_controllerなのでusers#destroyで行うのはちょっと違うかも（userの削除をする部分であって画像を削除する部分ではない。userの画像の削除はuser情報の一部を更新する、ということかなと。であればpdateですね）

2020-08-25 10:55 UTC, reiforu commented on app/models/user.rb
> +  has_one_attached :avatar
👍

2020-08-25 10:55 UTC, reiforu commented on app/views/conversations/_messages.html.erb
>  <% end %>
こういうのは極力WIPとして出したいですね
PRは完成品を出したいです

2020-08-25 10:55 UTC, reiforu commented on app/views/conversations/_messages.html.erb
>  <% end %>
何をしたいのかがちょっとわかりにくいかなと👀
adminでは画像を表示したくないということでしょうか？であればif user != adminのような条件を入れるのがいいと思います。

> @conversation(find(params[:id]))

このような記法はないはずですので、相手にわかるように正確に入力しましょう👍

2020-08-25 10:55 UTC, reiforu commented on app/views/conversations/index.html.erb
>  <% end %>
9〜13行目
ここは_messages.html.erbやuses/indexでも使われているのでDRYにしたいですかね👀

2020-08-25 10:55 UTC, reiforu commented on app/views/conversations/show.html.erb
> +<%= render "form", conversation: @conversation, message: @message %>
👍

2020-08-25 10:55 UTC, reiforu commented on app/views/users/registrations/edit.html.erb
> +
謎の空白👀

2020-08-25 10:55 UTC, reiforu commented on app/views/users/registrations/edit.html.erb
> +<% end %>
👍

2020-08-25 11:03 UTC, contekv commented on app/views/conversations/_messages.html.erb
>  <% end %>
すみません、次から未完成で出さないようにします💦
指摘頂いた通り、実装考えてみます。

次から正確に伝えるように努力します💦

2020-08-25 11:03 UTC, contekv commented on app/controllers/conversations_controller.rb
>      if @conversation.present?
すみません、気をつけます💦

2020-08-25 11:07 UTC, contekv commented on app/views/users/registrations/edit.html.erb
> +
申し訳ないです💦

2020-08-25 11:19 UTC, contekv commented on app/controllers/users/registrations_controller.rb
>  end
改めて動作確認しましたが、どうやらpurge処理を書かなくともpurgeしてattachしてくれているみたいです。logにもDeletedが残っておりました。

2020-08-27 02:52 UTC, reiforu requested changes

2020-08-27 02:52 UTC, reiforu commented on app/controllers/conversations_controller.rb
>      if @conversation.present?
直っていませんね👀

2020-08-27 02:52 UTC, reiforu commented on app/controllers/users_controller.rb
>  end
13行目漏れてましたね。というか後から追加とかされました？
ここfind_byの使い方そろそろわかっておきたいです。。

2020-08-27 02:52 UTC, reiforu commented on app/views/conversations/_avatars.html.erb
> +<% end %>
これと_avatar.html.erbの違いってなんでしょう？🤔
これだとそのDRYじゃないかなって思います。どちらか1つにまとめれるかなと

2020-08-27 02:52 UTC, reiforu commented on app/views/conversations/_messages.html.erb
>  <% end %>
ここ書き方は人それぞれではあるんですけど、
16行目のように1行で書くなら、12〜14行目も1行で書いたほうがいいかな？と思いました👍

2020-08-27 02:52 UTC, reiforu commented on app/views/users/_avatar.html.erb
> +<% end %>
これもですね。今同じようなファイルが3つありますね👀
結局はconversationかconverかuserを使いたいのですから、それを使い回せるような1つのファイルを作りたいです。

2020-08-27 09:45 UTC, contekv commented on app/views/users/_avatar.html.erb
> +<% end %>
承知しました！

2020-08-27 09:46 UTC, contekv commented on app/views/conversations/_avatars.html.erb
> +<% end %>
使い回せるファイルに修正します！

2020-08-27 09:49 UTC, contekv commented on app/controllers/users_controller.rb
>      user.avatar.purge
find_byとfind明確に分かっていないので調べておきますね！💦

2020-08-27 09:57 UTC, contekv commented on app/controllers/users_controller.rb
>  end
これは元々このままでした。
find_byとfindしっかり調べておきます💦

2020-08-31 06:11 UTC, reiforu approved these changes
LGTM！

2020-08-31 06:11 UTC, reiforu commented on app/controllers/users_controller.rb
>      user.avatar.purge
ここはfindのままでもよかったです👍
find_by(params[:id)のような使い方が正しくないということでした。このままでOK、修正は不要です

2020-08-31 06:11 UTC, reiforu commented on app/views/users/index.html.erb
> +  <%= render "/users/shared/avatar", user: user %><hr>
そうですね！正しくパーシャルを使えましたね👍

2020-08-31 06:40 UTC, merged