Medicine notebook
contekv/portfolio pull request #8
Opened 2020-09-03 08:00 UTC by contekv

コードレビューよろしくお願いします。

2020-09-03 08:04 UTC, contekv commented on app/controllers/admins_controller.rb
> +end
管理者専用のホーム画面作成することにしました。

2020-09-03 08:12 UTC, contekv commented on app/views/kaminari/_first_page.html.erb
> +<%# Link to the "First" page
すみません、kaminari view今後のカスタマイズのために先に追加しています。

2020-09-03 08:43 UTC, reiforu requested changes
全体的に少しずつ書けるようになってきたかなと思いました👍
ただ毎回指摘している部分があるのも事実なので、push前に確認するようにしたいです！

2020-09-03 08:43 UTC, reiforu commented on app/controllers/conversations_controller.rb
> +    @all_convers = Conversation.where(user_id: user).page(params[:page])
`Conversation.where(user: user)` か
`Conversation.where(user_id: user.id)` が望ましいです。

2020-09-03 08:43 UTC, reiforu commented on app/controllers/medicines_controller.rb
> +end
ここのfind_byはすべてfindに変えましょうか。
レコードがあること前提のページではfindを使いたいですね。
レコードがないときに例外ではなくfalseが返ってしまうので

2020-09-03 08:43 UTC, reiforu commented on app/views/medicines/show.html.erb
> +<%= render "form", user: @user, medicine: @medicine if current_user != @admin %>
5行目
できるだけ英単語にしたいです。mediだとよりかはmedicineとしたいですね。
他の人が見たときにパッと見わかるようにしたいです

2020-09-03 08:43 UTC, reiforu commented on app/controllers/medicines_controller.rb
> +end
15, 28, 37行目
現状、更新されなかった場合にメッセージが表示されずただ前の画面に戻るだけのようです。
そのような設計なら大丈夫ですが、一応確認させてください。

2020-09-03 08:43 UTC, reiforu commented on app/views/kaminari/_first_page.html.erb
> +<%# Link to the "First" page
であればカスタマイズするときに作るべきです。それか、カスタマイズまで終えてからpushしてレビュー依頼出すべきかなと。
今必要のないブランチであるならpushしたくないので、push対象から外すか実装までしてほしいです。

2020-09-03 08:43 UTC, reiforu commented on app/controllers/medicines_controller.rb
> +end
47行目
medicine_paramsは親子関係のあるクラスから呼ぶんでしょうか？
このコントローラ内でしか呼ばないならprotectedよりはprivateにしたいです。

2020-09-03 08:43 UTC, reiforu commented on app/views/medicines/record.html.erb
> +<% end %>
4行目
@medicinesを回すのですから、その1つ1つはmedicineな気がしました。
reだと何のことかわからないので修正してほしいです👍
何の配列を回しているか意識したいですね。

全体的にeachの部分を確認して修正してください👍

2020-09-03 08:43 UTC, reiforu commented on app/views/medicines/show.html.erb
> +<%= render "form", user: @user, medicine: @medicine if current_user != @admin %>
4〜19行目
record.html.erbの3〜15行目とだいぶ似ていませんか？
パーシャル作ってDRYにしたいかなと思いました。

2020-09-03 08:43 UTC, reiforu commented on app/views/medicines/record.html.erb
> +<% end %>
コントローラで作成している@userってこちらで使っていますか？👀
そろそろできるようになりたいですし、毎回伝えている気がします。push前に確認しましょう👍

2020-09-03 08:43 UTC, reiforu commented on app/views/medicines/record.html.erb
> +<% end %>
他のファイルについても、使ってないのにインスタンス変数作ってたりしませんか？
すべてのアクションとそれに対応するviewファイルを確認してください👍

2020-09-06 08:58 UTC, contekv commented on app/views/kaminari/_first_page.html.erb
> +<%# Link to the "First" page
承知しました。次回からは気をつけます💦

2020-09-06 09:00 UTC, contekv commented on app/controllers/conversations_controller.rb
> +    @all_convers = Conversation.where(user_id: user).page(params[:page])
Conversation.where(user: user)でも取得できることを知らなかったです。
少し学習してみます

2020-09-06 09:07 UTC, contekv commented on app/views/medicines/show.html.erb
> +<%= render "form", user: @user, medicine: @medicine if current_user != @admin %>
> 5行目
> できるだけ英単語にしたいです。mediだとよりかはmedicineとしたいですね。
> 他の人が見たときにパッと見わかるようにしたいです

命名しっかり意識するようにします。

2020-09-06 09:22 UTC, contekv commented on app/views/medicines/record.html.erb
> +<% end %>
> コントローラで作成している@userってこちらで使っていますか？👀
> そろそろできるようになりたいですし、毎回伝えている気がします。push前に確認しましょう👍

見落としていました💦　注意します。

2020-09-06 09:23 UTC, contekv commented on app/views/medicines/record.html.erb
> +<% end %>
> 4行目
> @medicinesを回すのですから、その1つ1つはmedicineな気がしました。
> reだと何のことかわからないので修正してほしいです👍
> 何の配列を回しているか意識したいですね。
> 
> 全体的にeachの部分を確認して修正してください👍


each文の命名気をつけるようにします。
パッと見でわかるように心掛けます。

2020-09-07 05:40 UTC, contekv commented on app/controllers/medicines_controller.rb
> +end
> ここのfind_byはすべてfindに変えましょうか。
> レコードがあること前提のページではfindを使いたいですね。
> レコードがないときに例外ではなくfalseが返ってしまうので

承知しました。変更しておきます。

2020-09-07 05:41 UTC, contekv commented on app/controllers/medicines_controller.rb
> +end
> 47行目
> medicine_paramsは親子関係のあるクラスから呼ぶんでしょうか？
> このコントローラ内でしか呼ばないならprotectedよりはprivateにしたいです。

protectedとprivate全く一緒と思っていました💦
確認しておきます。

2020-09-08 07:47 UTC, contekv commented on app/controllers/medicines_controller.rb
> +end
> 15, 28, 37行目
> 現状、更新されなかった場合にメッセージが表示されずただ前の画面に戻るだけのようです。
> そのような設計なら大丈夫ですが、一応確認させてください。

不自然な設計ですよね💦
書き加えておきます！

2020-09-08 11:55 UTC, reiforu requested changes
あと少しです！

2020-09-08 11:55 UTC, reiforu commented on app/controllers/medicines_controller.rb
> +end
9行目
マジックナンバーを使用しているので、定数として定義してください。

2020-09-08 11:55 UTC, reiforu commented on app/controllers/medicines_controller.rb
> +end
13行目
リダイレクト先が同じならDRYにしたいです。

```
message = @medicine.save ? "お薬が登録されました" : "お薬が登録されませんでした"
redirect_to medicine_path(@medicine.user), alert: message
```

2020-09-08 11:55 UTC, reiforu commented on app/controllers/conversations_controller.rb
>    protected
これ前指摘しなかったんですけど、やっぱり気になるので確認させてください。
Conversation作ると必ずuserが結びつくという認識でしたが違いますか？👀
であれば `Conversation.all.page(params[:page])`でいいのかな？と思いました！
一度Conversationのカウント数を比較してみてください👍

2020-09-08 11:55 UTC, reiforu commented on app/views/medicines/_medicines.html.erb
> +<% end %>
renderしてから配列で回すとパフォーマンス的にあまりよくないです。
renderにはcollectionという、eachを書かなくても配列渡せば勝手に回してくれるメソッドがあるので
`render collection railsガイド`などで調べてみてください👍

2020-09-08 15:19 UTC, contekv commented on app/controllers/medicines_controller.rb
> +end
> 9行目
> マジックナンバーを使用しているので、定数として定義してください。

承知しました！

2020-09-08 15:20 UTC, contekv commented on app/controllers/medicines_controller.rb
> +end
> 13行目
> リダイレクト先が同じならDRYにしたいです。
> 
> ```
> message = @medicine.save ? "お薬が登録されました" : "お薬が登録されませんでした"
> redirect_to medicine_path(@medicine.user), alert: message
> ```

おお！！！このようなDRYもできるのですね！
感動してしまいました。

2020-09-08 15:36 UTC, contekv commented on app/controllers/conversations_controller.rb
>    protected
Conversationは必ずuserが結びつく設計にするつもりでした！
このままだと外部キー設定した意味があまりないですよね💦
書き換えておきます！

2020-09-09 08:13 UTC, contekv commented on app/views/medicines/_medicines.html.erb
> +<% end %>
承知しました！
確認してみます。

2020-09-10 10:46 UTC, reiforu approved these changes
LGTM出しておきますが、1点気になる箇所ありましたので直しておいてください👍

2020-09-10 10:46 UTC, reiforu commented on app/views/medicines/record.html.erb
> +  <%= render partial: "medicines", collection: @medicines %>
自分で調べて実装できるようになってきましたね！👍
ただ、パーシャル内部で使う変数って複数形でしたっけ？🤔
今これってエラーでませんか？？

https://railsguides.jp/layouts_and_rendering.html#%E3%82%B3%E3%83%AC%E3%82%AF%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%92%E3%83%AC%E3%83%B3%E3%83%80%E3%83%AA%E3%83%B3%E3%82%B0%E3%81%99%E3%82%8B

2020-09-10 11:29 UTC, merged